### ISSUE TITLE
Explicitly direct user to various files in #11?

### ISSUE THREAD

**Issue by msespos** [rlmoser99/ruby_rspec_TOP#69]
Do we maybe want to explicitly direct the user to 11_shared_example_spec.rb at the top of the "dog spec" and "cat spec" files? As in “START HERE” in 11_shared_example_spec.rb, and “START AT 11_shared_example_spec.rb" in the other two? Or something less shouty perhaps. I just think it might help to make it clear where the starting point is (which IMO is 11_shared_example_spec.rb).

**Comment by rlmoser99** [comment]
Yes, I see your point of view and agree with you. Especially since we have recently started pointing people to the 'right' file in some of the later ones.

Do you think we should rename the file, for example:
11a_shared_example_spec.rb
11b_cat_spec.rb
11c_dog_spec.rb

Then, the 'a' could signify the starting file. This could be done for 15 & 16 too.

**Comment by msespos** [comment]
I like using 11a, 11b, 11c and the same system for the others.
